// <auto-generated />
using System;
using EuphoriaCommerce.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuphoriaCommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121143611_seed-colors-sizes-data")]
    partial class seedcolorssizesdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CartDomain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BrandLogoUrl");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("BrandName");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BrandId");

                    b.HasIndex("Name");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CategoryDescription");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("CategoryName");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("HexCode");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ColorName");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ColorId");

                    b.HasIndex("Name");

                    b.ToTable("Colors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7b39dcc-5795-7e5c-b1f4-5670a1da7ff4"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 361, DateTimeKind.Utc).AddTicks(4448),
                            CreatedBy = "System",
                            HexCode = "#FF0000",
                            IsDeleted = false,
                            Name = "Red"
                        },
                        new
                        {
                            Id = new Guid("44bc447d-2a9c-3756-8800-a503f10f3d89"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1301),
                            CreatedBy = "System",
                            HexCode = "#0000FF",
                            IsDeleted = false,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = new Guid("1af23b93-d5fd-0d5a-a283-845fed0e7bbd"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1847),
                            CreatedBy = "System",
                            HexCode = "#00FF00",
                            IsDeleted = false,
                            Name = "Green"
                        },
                        new
                        {
                            Id = new Guid("57fb06b4-9fb2-6f57-b186-4fbb37f02380"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1879),
                            CreatedBy = "System",
                            HexCode = "#000000",
                            IsDeleted = false,
                            Name = "Black"
                        },
                        new
                        {
                            Id = new Guid("c19f6137-5330-2b58-bcb7-da3d24ceb159"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1890),
                            CreatedBy = "System",
                            HexCode = "#FFFFFF",
                            IsDeleted = false,
                            Name = "White"
                        },
                        new
                        {
                            Id = new Guid("07f62635-d4bc-1a55-90bc-05f814579a42"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1900),
                            CreatedBy = "System",
                            HexCode = "#FFFF00",
                            IsDeleted = false,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("59630754-c7fd-f051-a000-b9ae15b96f8b"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1912),
                            CreatedBy = "System",
                            HexCode = "#FFC0CB",
                            IsDeleted = false,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = new Guid("4f6f5732-c0ed-635f-8203-53af6a8aac66"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1972),
                            CreatedBy = "System",
                            HexCode = "#800080",
                            IsDeleted = false,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = new Guid("ab6afb09-94a7-7b5a-bffd-bc9cbb9b3498"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(1991),
                            CreatedBy = "System",
                            HexCode = "#FFA500",
                            IsDeleted = false,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = new Guid("0b35473a-7c7d-9156-a01c-cff5ad5d3aca"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 366, DateTimeKind.Utc).AddTicks(2003),
                            CreatedBy = "System",
                            HexCode = "#A52A2A",
                            IsDeleted = false,
                            Name = "Brown"
                        });
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.GenderCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenderCategories");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("SizeName");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SizeType");

                    b.HasKey("Id")
                        .HasName("PK_SizeId");

                    b.HasIndex("Name");

                    b.ToTable("Sizes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8d457c0-373b-e05e-b477-b22feeb4f238"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4818),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "XXS",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("d2d0b1bd-0d76-ae50-b3b0-2dff5258e945"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4915),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "XS",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("9c62aa02-168b-175d-a44f-3a0efec2feed"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4932),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "S",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("dde63ac6-c94f-dd59-a669-70e827d13f7c"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4944),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "M",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("98e060d1-ca6a-1457-b14a-16f29ec605af"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4956),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "L",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("d1d0f9a2-026d-0e52-b369-e6029d9e5929"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4968),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "XL",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("ab3fa6a9-48b9-f056-9948-c35e2bf2974e"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4983),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "XXL",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("b1b2a3ff-83e4-345d-8cb7-90a05daa28b2"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(4995),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "3XL",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("13cf1017-741a-a25f-a8fc-a17f102841bc"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5006),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "4XL",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("d1e45fd5-1c39-3858-a407-69dea25e2cf7"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5016),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "5XL",
                            SizeType = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("e34c385b-8c2d-f05e-abc3-a139d4cac0a2"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5064),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "38",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("f41235ca-a9df-035a-969c-5a670a4c91a1"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5078),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "39",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("34133eaf-b928-5c52-95bc-59fe534248e6"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5090),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "40",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("b2221f76-59c1-0b5d-b87e-0b606f990ba4"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5113),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "41",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("b3cecf92-579d-1459-ad8b-14d0e37643de"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5127),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "42",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("55dd8602-9b2c-9a5a-a9ec-b3759e7b9477"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5138),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "43",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("2fc4fb98-dcae-4952-a397-cb5962ea3a3f"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5149),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "44",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("514364fb-0d56-9652-be6d-a332236b1f8d"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5289),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "45",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("95f42efe-15a1-6155-9729-49784c16bf23"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5299),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "46",
                            SizeType = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("45fc7b82-0887-b450-8200-9c9c9836f7e4"),
                            CreatedAt = new DateTime(2025, 11, 21, 14, 36, 10, 367, DateTimeKind.Utc).AddTicks(5309),
                            CreatedBy = "System",
                            IsDeleted = false,
                            Name = "47",
                            SizeType = "Shoes"
                        });
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.OrderDomain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ProductDescription");

                    b.Property<Guid>("GenderCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ProductName");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ProductPrice");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalStock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GenderCategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("BadgeName");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BadgeId");

                    b.HasIndex("Name");

                    b.HasIndex("ProductId");

                    b.ToTable("Badges", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageUrl");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("TagName");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_TagId");

                    b.HasIndex("Name");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PriceOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ProductPrice");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ProductVariantId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ReviewDomain.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_FeedbackId");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.WishlistDomain.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_WishlistId");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists", (string)null);
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_UserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductProductTag");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CartDomain.Cart", b =>
                {
                    b.OwnsMany("EuphoriaCommerce.Domain.Entities.CartDomain.CartItem", "CartItems", b1 =>
                        {
                            b1.Property<Guid>("CartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("CartId", "Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("CartItem");

                            b1.WithOwner()
                                .HasForeignKey("CartId");

                            b1.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", "Product")
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Product");
                        });

                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.OrderDomain.Order", b =>
                {
                    b.OwnsMany("EuphoriaCommerce.Domain.Entities.OrderDomain.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("OrderItem");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.Entities.CatalogDomain.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Brand_Id");

                    b.HasOne("EuphoriaCommerce.Domain.Entities.CatalogDomain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category_Id");

                    b.HasOne("EuphoriaCommerce.Domain.Entities.CatalogDomain.GenderCategory", "GenderCategory")
                        .WithMany("Products")
                        .HasForeignKey("GenderCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Gender_Id");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("GenderCategory");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductBadge", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", "Product")
                        .WithMany("Badges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Badge_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductImage", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Product_image");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductVariant", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.Entities.CatalogDomain.Color", "Color")
                        .WithMany("Variants")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Variant_Color_Id");

                    b.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Variant_Product_Id");

                    b.HasOne("EuphoriaCommerce.Domain.Entities.CatalogDomain.Size", "Size")
                        .WithMany("Variants")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Variant_Size_Id");

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ReviewDomain.Feedback", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", "Product")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Product_Id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.WishlistDomain.Wishlist", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlist_Product_Id");

                    b.HasOne("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", "ApplicationUser")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlist_User_Id");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.OwnsOne("EuphoriaCommerce.Domain.IdentityEntities.UserProfile", "UserProfile", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Bio")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("City")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Country")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("FullName")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("ProfileImageUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SecondName")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Street")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.HasKey("ApplicationUserId");

                            b1.ToTable("Users");

                            b1.WithOwner("ApplicationUser")
                                .HasForeignKey("ApplicationUserId");

                            b1.Navigation("ApplicationUser");
                        });

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuphoriaCommerce.Domain.Entities.ProductDomain.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Color", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.GenderCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.CatalogDomain.Size", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.Entities.ProductDomain.Product", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Feedbacks");

                    b.Navigation("ProductImages");

                    b.Navigation("Variants");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("EuphoriaCommerce.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
